# __Consumo de energía en edificios de la Comunidad de Madrid e instalaciones fotovoltaicas__

##### _Grupo Erasmus_

In [88]:
import pandas as pd

# Intentar con la codificación correcta
consumo = pd.read_csv('consumo_energia.csv', encoding='utf-8', sep=',')
Inventario = pd.read_csv('inventario_completo_limpio.csv', encoding='utf-8', sep=',')

consumo.columns = consumo.columns.str.lower()
Inventario.columns = Inventario.columns.str.lower()

# Mostrar las primeras filas para verificar
consumo

,año,mes,tipoedificio,edificio,direccion,distrito,código distrito,barrio,código barrio,coordenada-x,coordenada-y,longitud,latitud,sensor,tipo,clase,unidades,consumo
0,2020,3,Centros culturales y bibliotecas,Biblioteca Ana María Matute,"CALLE ISAAC ALBENIZ, 1 28019 MADRID",CARABANCHEL,11,SAN ISIDRO,113,"438873,92","4472154,36",-3.7202936410904,40.3977521494866,AMBIBAMMATUTE_General,Externo,Energía activa,kWh,13099.0
1,2020,3,Centros culturales y bibliotecas,Biblioteca Ana María Matute,"CALLE ISAAC ALBENIZ, 1 28019 MADRID",CARABANCHEL,11,SAN ISIDRO,113,"438873,92","4472154,36",-3.7202936410904,40.3977521494866,AMBIBAMMATUTE_General,Externo,Energía Reactiva,kvarh,104.0
2,2020,3,Centros culturales y bibliotecas,Biblioteca Ángel González,"CALLE GRANJA DE TORREHERMOSA, 1 28024 MADRID",LATINA,10,ALUCHE,104,"434962,85","4472100,21",-3.7663713097572,40.3969681670062,AMBIBAGONZALEZ_Electricidad_General,Externo,Energía activa,kWh,9688.0
3,2020,3,Centros culturales y bibliotecas,Biblioteca Ángel González,"CALLE GRANJA DE TORREHERMOSA, 1 28024 MADRID",LATINA,10,ALUCHE,104,"434962,85","4472100,21",-3.7663713097572,40.3969681670062,AMBIBAGONZALEZ_Electricidad_General,Externo,Energía Reactiva,kvarh,4262.0
4,2020,3,Centros culturales y bibliotecas,Biblioteca Ángel González,"CALLE GRANJA DE TORREHERMOSA, 1 28024 MADRID",LATINA,10,ALUCHE,104,"434962,85","4472100,21",-3.7663713097572,40.3969681670062,AMBIBAGONZALEZ_Gas_General,Externo,Gas,m3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23029,2024,10,Centros culturales y bibliotecas,Biblioteca Pablo Neruda,"CALLE ASCAO, 4 28017 MADRID",CIUDAD LINEAL,15,PUEBLO NUEVO,152,"445565,18",4475620,-3.641334923876934,40.42963395178173,[Biblioteca Pablo Neruda][0702] Consumo Biblio...,PROCESADO,Energía activa,kWh,0.0
23030,2024,10,Centros culturales y bibliotecas,CMM Orcasur,"AVENIDA ORCASUR, 60 28041 MADRID",USERA,12,ORCASUR,122,"440558,44","4468830,39",-3.69954710390932,40.368311695306396,[CMM Orcasur][1096] Electricidad General Conta...,PROCESADO,Energía activa,kWh,0.0
23031,2024,10,Centros culturales y bibliotecas,Biblioteca Gabriel García Márquez,"PLAZA PUEBLO, 2 (CENTRO CULTURAL ORCASUR) ...",USERA,12,ORCASUR,122,"440484,3","4468711,09",-3.7014543907797677,40.36697564023111,[Biblioteca Gabriel García Márquez][1095] Elec...,PROCESADO,Energía activa,kWh,0.0
23032,2024,10,Centros escolares,CEIP Ntra Sra de la Almudena,"CALLE LOPE DE RUEDA, 48, 28009 MADRID",RETIRO,3,IBIZA,34,"442741,9","4474561,6",-3.674934214335211,40.419712628103916,[CEIP Ntra Sra de la Almudena][0483] Electrici...,EXTERNO,Energía activa,kWh,0.0
23033,2024,10,Centros culturales y bibliotecas,CC El Torito,"AVENIDA MORATALAZ, 130 28030 MADRID",MORATALAZ,14,VINATEROS,146,"445135,88","4473047,36",-3.645480705416855,40.40627804229188,[CC El Torito][1017] Consumo total,PROCESADO,Energía activa,kWh,0.0

In [90]:
Inventario

,número,código ayto,centro,dirección,coordenada-x,coordenada-y,latitud,longitud,superficie (m2),uso del edificio,adscripción,distrito,potencia kwp,empresa instaladora,puesta en servicio
0,1.0,2178.0,BIBLIOTECA ÁNGEL GONZALEZ,"C/ GRANJA DE TORREHERMOSA, 2",434954.0,4472113.0,40.397075,-3.766489,1743.961867,cultural,AG Cultura Turismo y Deportes,Latina,20.000000,ORTIZ,2019-07-31
1,2.0,782.0,BIBLIOTECA IVÁN DE VARGAS,"C/ DOCTOR LETAMENDI, 1",439775.0,4473962.0,40.414103,-3.709859,1743.961867,cultural,AG Cultura Turismo y Deportes,Centro,3.000000,ORTIZ,2019-07-24
2,3.0,2096.0,BIBLIOTECA EUGENIO TRIAS (CASA FIERAS),"AV/ MENENDEZ PELAYO , 10-3 BJ",442345.0,4474221.0,40.416609,-3.679593,1743.961867,cultural,AG Cultura Turismo y Deportes,Retiro,18.511834,ORTIZ,2019-07-24
3,4.0,1046.0,PLANETARIO,AV/ PLANETARIO 16,441830.0,4471375.0,40.390944,-3.685391,3.062000,cultural,AG Cultura Turismo y Deportes,Arganzuela,25.000000,FULTON,2019-09-13
4,5.0,2143.0,MADRID EMPRENDE,"C/CIDRO, 3",436689.0,4468938.0,40.368616,-3.745730,1242.692833,administrativo,"AG Economía, Innovación y Empleo",Carabanchel,10.000000,Empresa desconocida,2019-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,171.0,603.0,CENTRO MUNICIPAL DE RECOGIDAS TRECE ROSAS,"AVENIDA DE LAS TRECE ROSAS, 5, 28017 MADRID",445062.0,4475080.0,40.424542,-3.647631,1505.375826,medioambiental,"Area de Gobierno de Urbanismo, Medioambiente y...",CIUDAD LINEAL,10.000000,Empresa desconocida,2024-07-01
616,172.0,2656.0,CDM EL QUIJOTE,"CALLE NUMANCIA,2",439587.0,4478360.0,40.453707,-3.712486,4661.848686,deportivo,JMD Moncloa Aravaca,MONCLOA - ARAVACA,20.000000,Empresa desconocida,2024-09-12
617,173.0,35.0,CDM MOSCARDO,CALLE PILAR DE ZARAGOZA 93,440125.0,4471120.0,40.388522,-3.705459,4661.848686,deportivo,JMD Salamanca,SALAMANCA,10.000000,Empresa desconocida,2024-09-11
618,174.0,1918.0,CID VILLA DE VALLECAS / OAC,CALLE REAL DE ARGANDA 64,447858.0,4470029.0,40.379215,-3.614259,1505.375826,seguridad,JMD Villa de Vallecas,VILLA DE VALLECAS,10.000000,Empresa desconocida,2024-09-11
619,175.0,1918.0,ALMACEN BOMBEROS VILLA DE VALLECAS,CALLE EL REAL DE SAN VICENTE 61,446228.0,4468926.0,40.369172,-3.633370,3330.040429,seguridad,JMD Villa de Vallecas,VILLA DE VALLECAS,33.000000,Empresa desconocida,2024-04-03

In [92]:
#  Ver cuántos valores nulos hay en cada columna
print("Número de valores nulos por columna:")
print(Inventario.isnull().sum())

Número de valores nulos por columna:
número                 0
código ayto            0
centro                 0
dirección              0
coordenada-x           0
coordenada-y           0
latitud                0
longitud               0
superficie (m2)        0
uso del edificio       0
adscripción            0
distrito               0
potencia kwp           0
empresa instaladora    0
puesta en servicio     0
dtype: int64

In [94]:
#  Ver cuántos valores nulos hay en cada columna
print("Número de valores nulos por columna:")
print(consumo.isnull().sum())

Número de valores nulos por columna:
año                0
mes                0
tipoedificio       0
edificio           0
direccion          0
distrito           0
código distrito    0
barrio             0
código barrio      0
coordenada-x       0
coordenada-y       0
longitud           0
latitud            0
sensor             0
tipo               0
clase              0
unidades           0
consumo            0
dtype: int64

In [96]:
DISTRITO = consumo.groupby(['distrito']).count()
conteo_dist_consumo = DISTRITO.sort_values(by=['edificio'], ascending=True)
conteo_dist_consumo

,año,mes,tipoedificio,edificio,direccion,código distrito,barrio,código barrio,coordenada-x,coordenada-y,longitud,latitud,sensor,tipo,clase,unidades,consumo
distrito,,,,,,,,,,,,,,,,,
#N/D,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SALAMANCA,558,558,558,558,558,558,558,558,558,558,558,558,558,558,558,558,558
CHAMBERI,586,586,586,586,586,586,586,586,586,586,586,586,586,586,586,586,586
TETUAN,673,673,673,673,673,673,673,673,673,673,673,673,673,673,673,673,673
BARAJAS,706,706,706,706,706,706,706,706,706,706,706,706,706,706,706,706,706
VILLA DE VALLECAS,735,735,735,735,735,735,735,735,735,735,735,735,735,735,735,735,735
MORATALAZ,790,790,790,790,790,790,790,790,790,790,790,790,790,790,790,790,790
VICALVARO,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813,813
CHAMARTIN,869,869,869,869,869,869,869,869,869,869,869,869,869,869,869,869,869
SAN BLAS - CANILLEJAS,891,891,891,891,891,891,891,891,891,891,891,891,891,891,891,891,891
ARGANZUELA,923,923,923,923,923,923,923,923,923,923,923,923,923,923,923,923,923
HORTALEZA,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040,1040
MONCLOA - ARAVACA,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066,1066
FUENCARRAL - EL PARDO,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135,1135
CARABANCHEL,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158,1158
PUENTE DE VALLECAS,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362
RETIRO,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412,1412
CIUDAD LINEAL,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468,1468
USERA,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491,1491
VILLAVERDE,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698,1698
LATINA,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722
CENTRO,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937,1937

In [98]:
DISTRITO = Inventario.groupby(['distrito']).count()
conteo_dist_inventario = DISTRITO.sort_values(by=['centro'], ascending=True)
conteo_dist_inventario

,número,código ayto,centro,dirección,coordenada-x,coordenada-y,latitud,longitud,superficie (m2),uso del edificio,adscripción,potencia kwp,empresa instaladora,puesta en servicio
distrito,,,,,,,,,,,,,,
Villaverde,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Puente de Vallecas,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Villaverde,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Salamanca,2,2,2,2,2,2,2,2,2,2,2,2,2,2
PUENTE DE VALLECAS,2,2,2,2,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Villaverde,20,20,20,20,20,20,20,20,20,20,20,20,20,20
CIUDAD LINEAL,21,21,21,21,21,21,21,21,21,21,21,21,21,21
RETIRO,22,22,22,22,22,22,22,22,22,22,22,22,22,22
MONCLOA - ARAVACA,25,25,25,25,25,25,25,25,25,25,25,25,25,25
VILLAVERDE,32,32,32,32,32,32,32,32,32,32,32,32,32,32

In [100]:
# Eliminar columnas innecesarias
columnas_a_eliminar = ['número', 'código ayto', 'coordenada-x', 'coordenada-y', 'latitud', 'longitud','adscripción', 'superficie (m2)']
Inventario = Inventario.drop(columns=columnas_a_eliminar)

# Verificar el resultado
Inventario.head()

,centro,dirección,uso del edificio,distrito,potencia kwp,empresa instaladora,puesta en servicio
0,BIBLIOTECA ÁNGEL GONZALEZ,"C/ GRANJA DE TORREHERMOSA, 2",cultural,Latina,20.000000,ORTIZ,2019-07-31
1,BIBLIOTECA IVÁN DE VARGAS,"C/ DOCTOR LETAMENDI, 1",cultural,Centro,3.000000,ORTIZ,2019-07-24
2,BIBLIOTECA EUGENIO TRIAS (CASA FIERAS),"AV/ MENENDEZ PELAYO , 10-3 BJ",cultural,Retiro,18.511834,ORTIZ,2019-07-24
3,PLANETARIO,AV/ PLANETARIO 16,cultural,Arganzuela,25.000000,FULTON,2019-09-13
4,MADRID EMPRENDE,"C/CIDRO, 3",administrativo,Carabanchel,10.000000,Empresa desconocida,2019-09-13

In [102]:
# Cambiar el nombre de las columnas
nuevos_nombres = {
    'centro': 'edificio',
    'uso del edificio': 'tipo del edificio'
}

Inventario = Inventario.rename(columns=nuevos_nombres)

# Verificar el cambio
Inventario.head()

,edificio,dirección,tipo del edificio,distrito,potencia kwp,empresa instaladora,puesta en servicio
0,BIBLIOTECA ÁNGEL GONZALEZ,"C/ GRANJA DE TORREHERMOSA, 2",cultural,Latina,20.000000,ORTIZ,2019-07-31
1,BIBLIOTECA IVÁN DE VARGAS,"C/ DOCTOR LETAMENDI, 1",cultural,Centro,3.000000,ORTIZ,2019-07-24
2,BIBLIOTECA EUGENIO TRIAS (CASA FIERAS),"AV/ MENENDEZ PELAYO , 10-3 BJ",cultural,Retiro,18.511834,ORTIZ,2019-07-24
3,PLANETARIO,AV/ PLANETARIO 16,cultural,Arganzuela,25.000000,FULTON,2019-09-13
4,MADRID EMPRENDE,"C/CIDRO, 3",administrativo,Carabanchel,10.000000,Empresa desconocida,2019-09-13

In [110]:
# Guardar el dataset modificado en un nuevo archivo CSV
Inventario.to_csv('inventario_modificado.csv', index=False, encoding='utf-8')